all:
	g++ advanced_stack.cpp frontend.cpp frontend_main.cpp logs.cpp MyGeneralFunctions.cpp Syntax_analyzer.cpp Tree.cpp -o Frontend.out
	./Frontend.out

debug:
	g++ -g advanced_stack.cpp frontend.cpp frontend_main.cpp logs.cpp MyGeneralFunctions.cpp Syntax_analyzer.cpp Tree.cpp -o Frontend.out
	gdb ./Frontend.out