all:
	g++ au_stack.cpp inverse.cpp logs.cpp MyGeneralFunctions.cpp Tree.cpp treeSyntaxAnalyzer.cpp -o inverse.out
	./inverse.out

debug:
	g++ -g au_stack.cpp inverse.cpp logs.cpp MyGeneralFunctions.cpp Tree.cpp treeSyntaxAnalyzer.cpp -o inverse.out
	gdb ./inverse.out